CREATE TABLE activity_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    activity_factor DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE objectives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    objective_name VARCHAR(100) NOT NULL,
    score INTEGER NOT NULL
);

CREATE TABLE allergies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE allergy_ingredients (
    allergy_id BIGINT NOT NULL,
    ingredient_name VARCHAR(100) NOT NULL,
    CONSTRAINT fk_allergy_ingredients_allergy FOREIGN KEY (allergy_id) REFERENCES allergies (id)
);

CREATE TABLE user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    gender VARCHAR(25) NOT NULL,
    height DOUBLE PRECISION NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    user_score INTEGER NOT NULL,
    birth_date VARCHAR(25) NOT NULL,
    activity_level_id BIGINT NOT NULL,
    objective_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_profiles_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_profiles_activity_level FOREIGN KEY (activity_level_id) REFERENCES activity_levels (id),
    CONSTRAINT fk_user_profiles_objective FOREIGN KEY (objective_id) REFERENCES objectives (id)
);

CREATE TABLE user_profile_allergies (
    user_profile_id BIGINT NOT NULL,
    allergy_id BIGINT NOT NULL,
    CONSTRAINT fk_user_profile_allergies_profile FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id),
    CONSTRAINT fk_user_profile_allergies_allergy FOREIGN KEY (allergy_id) REFERENCES allergies (id)
);

CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25) NOT NULL,
    email VARCHAR(25) NOT NULL,
    password VARCHAR(25) NOT NULL,
    is_active BOOLEAN NOT NULL,
    birth_date VARCHAR(25) NOT NULL,
    user_profile_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_profiles_user_profile UNIQUE (user_profile_id),
    CONSTRAINT fk_profiles_user_profile FOREIGN KEY (user_profile_id) REFERENCES user_profiles (id)
);
